#!/usr/bin/env node
// Regenerates public/sitemap.xml from scripts/public-routes.mjs.
//
// Runs as the `prebuild` npm script, so every deploy (which does
// `npm install && npm run build` on the server) publishes a sitemap that
// matches the routes currently shipped — no manual step to forget.
//
// <lastmod> comes from the last commit that touched each page's source file,
// which is a truthful "content last changed" signal. On a server whose deploy
// does a shallow clone (or when git is unavailable) we fall back to the file's
// mtime rather than emitting a fake date.

import { execFileSync } from 'node:child_process';
import { statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PUBLIC_ROUTES, SITE_ORIGIN } from './public-routes.mjs';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** ISO-8601 date (YYYY-MM-DD) of the last commit touching `file`, or null. */
function lastCommitDate(file) {
    try {
        const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
            cwd: projectRoot,
            encoding: 'utf8',
            stdio: ['ignore', 'pipe', 'ignore'],
        }).trim();
        return out || null;
    } catch {
        return null;
    }
}

function lastModified(file) {
    const fromGit = lastCommitDate(file);
    if (fromGit) return fromGit;
    try {
        return statSync(resolve(projectRoot, file)).mtime.toISOString().slice(0, 10);
    } catch {
        return null;
    }
}

const urls = PUBLIC_ROUTES.map(({ path, source, changefreq, priority }) => {
    const lastmod = source ? lastModified(source) : null;
    return [
        '    <url>',
        `        <loc>${SITE_ORIGIN}${path}</loc>`,
        lastmod ? `        <lastmod>${lastmod}</lastmod>` : null,
        changefreq ? `        <changefreq>${changefreq}</changefreq>` : null,
        priority ? `        <priority>${priority}</priority>` : null,
        '    </url>',
    ]
        .filter(Boolean)
        .join('\n');
}).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand.
     Add or remove pages in scripts/public-routes.mjs instead. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

const outPath = resolve(projectRoot, 'public/sitemap.xml');
writeFileSync(outPath, xml, 'utf8');
console.log(`sitemap.xml: ${PUBLIC_ROUTES.length} URLs → ${outPath}`);
